substitutions:
  board: d1_mini

# I²C Bus
#i2c:
#  sda: GPIO21
#  scl: GPIO22
#  scan: true
#  frequency: 100kHz

#packages:
#  base: !include common-8266.yaml
#  chip: github://raidnet-ms/homenest/common/board/common-8266.yaml@main