substitutions:
  board: d1_mini

# I²C Bus
#i2c:
#  sda: D2
#  scl: D1
#  scan: true
#  frequency: 100kHz

packages:
  chip: !include common-8266.yaml
#  chip: github://raidnet-ms/homenest/common/board/common-8266.yaml@main