substitutions:
  name: ac-dc-relay-x4-mac
  friendly_name: ac-dc-relay-x4
  project_name: raidnet.relayx4
  project_version: 1.0.0
  comment: ESP32_Relay X4 AC/DC powered

  log_level: debug
  disable_entities:  'true' # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password


#esphome:
#  name: ac-dc-relay-x4
#  friendly_name: ac-dc-relay-x4

esp32:
  variant: esp32
  framework:
    type: esp-idf

switch:
  - platform: gpio
    pin: GPIO32
    name: "Relay 1"
  - platform: gpio
    pin: GPIO33
    name: "Relay 2"
  - platform: gpio
    pin: GPIO25
    name: "Relay 3"
  - platform: gpio
    pin: GPIO26
    name: "Relay 4"

status_led:
  pin: GPIO23





packages:
# Common Remote Packages
  base: github://raidnet-ms/homenest/common/device_base.yaml@main
#  chip: github://raidnet-ms/homenest/common/board/common-32-idf.yaml@main
#  board: github://raidnet-ms/homenest/common/board/d1_mini.yaml
  diagnostic: github://raidnet-ms/homenest/common/diagnostic.yaml@main