substitutions:
  name: esp32-c3
  friendly_name: esp32-c3-pico
  disable_entities:  "true"

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key

packages:
  board: !include common/board/wemos-c3-pico.yaml
  device: !include device/watermeter/packages.yaml