substitutions:
  name: castania3switch
  friendly_name: 3switch
  log_level: DEBUG #debug
  project_name: raidnet.sw
  project_version: 1.0.0
  board: nodemcuv2
  disable_entities:  "true" # Disabilitare in blocco entità superflue

packages:
# Local Common Packages
  board: !include common/board/common-8266.yaml

status_led:
  pin: 
    number: D4 #GPIO2
    inverted: true


switch:
  - platform: gpio
    pin:
      number: D5 #GPIO14
      inverted: true
    name: "Switch 1"

  - platform: gpio
    pin:
      number: D6 # GPIO12
      inverted: true
    name: "Switch 2"

  - platform: gpio
    pin:
      number: D7 #GPIO13
      inverted: true
    name: "Switch 3"
    