substitutions:
  name: esp32batt
  friendly_name: Esp32 Battery
  project_name: raidnet.esp32batt
  project_version: 1.0.0
  comment: comment

  log_level: debug
  disable_entities:  'true' # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password
  board: esp32dev


packages:
# Common Remote Packages
  base: github://raidnet-ms/homenest/common/device_base.yaml@main
  chip: github://raidnet-ms/homenest/common/board/common-32-idf.yaml@main
#  board: github://raidnet-ms/homenest/common/board/wemosbat.yaml
  diagnostic: github://raidnet-ms/homenest/common/diagnostic.yaml@main