substitutions:
  name: esp32batt2
  friendly_name: esp32batt2
  project_name: raidnet.majordomo
  project_version: 1.0.0
  log_level: debug
  disable_entities:  "true"




packages:
  board: !include common/board/wemosbat.yaml