substitutions:
  name: esp32cam
  friendly_name: Esp32 camera


  log_level: debug
  disable_entities:  'true' # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password


packages:
# Common Remote Packages
  base: github://raidnet-ms/homenest/common/device_base.yaml@main
  chip: github://raidnet-ms/homenest/common/board/common-32-idf.yaml@main
  board: github://raidnet-ms/homenest/device/esp32cam_aithinker.yaml
  diagnostic: github://raidnet-ms/homenest/common/diagnostic.yaml@main



##############################################################
#esp32:
#  framework:
#    type: esp-idf
#    sdkconfig_options:
#      CONFIG_ESP32_BROWNOUT_DET: "n"

psram:
  mode: quad
  speed: 40MHz


#i2c:
#  - id: camera_i2c
#    sda: GPIO26
#    scl: GPIO27

#esp32_camera:
#  external_clock:
#    pin: GPIO0
#    frequency: 10MHz
#  i2c_id: camera_i2c
#  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
#  vsync_pin: GPIO25
#  href_pin: GPIO23
#  pixel_clock_pin: GPIO22
#  power_down_pin: GPIO32



time:
  - platform: homeassistant
    id: homeassistant_time