substitutions:
  name: ikea-airq
  friendly_name: Ikea air quality


  disable_entities:  'true' # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password


packages:


# Device Remote Packages
  device: github://raidnet-ms/homenest/device/ikea-aq_test/manifest.yaml@main