substitutions:
  name: ikea-airq
  friendly_name: Ikea air quality


  disable_entities:  'true' # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password


remote_packages:
# Device Remote Packages
#  common: github://raidnet-ms/homenest/common/board/d1_mini.yaml@main
  device: github://raidnet-ms/homenest/device/ikea_aq_test/manifest.yaml@main