substitutions:
  name: ikeatest
  friendly_name: Ikea air quality


  disable_entities:  true # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password


remote_package:
# Device Remote Packages
#  core: github://raidnet-ms/homenest/common/board/d1_mini.yaml@main
#  core: github://raidnet-ms/homenest/common/board/common-base.yaml@main
#  device: github://raidnet-ms/homenest/device/ikeatest/manifest.yaml@main
  core: github://raidnet-ms/homenest/common/board/common-base.yaml@main
  url: github://raidnet-ms/homenest/device/ikeatest/
  ref: main
  refresh: 1m
  files:
    - device/irrigatore/*
    - device/irrigatore/config.yaml