substitutions:
  name: ikea-airq
  friendly_name: Ikea air quality
  project_name: raidnet.aq
  project_version: 1.0.0
  log_level: debug
  disable_entities:  "true" # Disabilitare in blocco entità superflue

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password

packages:
# Local Common Packages
  base: !include common/device_base.yaml
#  board: !include common/board/d1_mini.yaml
#  aqi: !include common/sensor/aqi.yaml

remote_packages:
  board: github://raidnet-ms/homenest/common/board/d1_mini.yaml
#  base: github://raidnet-ms/homenest/common/device_base.yaml@main
  aqi: github://raidnet-ms/homenest/common/sensor/aqi.yaml

i2c: # used by ccs811 and sht3xd
  sda: D2
  scl: D1
#  scan: false

switch:
  - platform: gpio
#    name: wake css811
    entity_category: config
    pin:
      number: D3  
      inverted: true
    id: wake
    restore_mode: ALWAYS_ON # Must be on on boot to retrieve data


uart: # used by pm1006 only rx needed
  rx_pin: D7
  baud_rate: 9600

# Calibrare sensore temperatura
sensor:
  - platform: sht3xd
    update_interval: 5min
#    address: 0x44
    temperature:
      name: "Temperatura"
      id: temp
      filters:
        - calibrate_linear:
#            - 0.0 -> 0.0
            - 24.87 -> 20.6
            - 27.6 -> 21.4
            - 34.1 -> 29.6

    humidity:
      name: "Umidità"
      id: hum
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 52.20 -> 60

  - platform: ccs811  # esiste il sensore con sensore temperatura 1080h integrato CJMCU-8128 CCS811
#    update_interval: 60s
#    version:
#      name: versione
#    address: 0x5A
    eco2:
      name: "eCO2 Value"
      id: eco2
      filters:
        - median:
        - throttle: 60s
        - heartbeat: 60s
    tvoc:
      name: "Total Volatile Organic Compound"
      id: tvoc
      filters:
        - median:
        - throttle: 60s
        - heartbeat: 60s
    temperature: temp
    humidity: hum
    baseline: 0xBFBD

  # Ikea Vindriktning PM2.5 sensor
  - platform: pm1006
    pm_2_5:
      name: "Particolato PM25"
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
#            send_first_at: 1 #default 1


  - platform: absolute_humidity
    name: "Absolute Humidity"
    temperature: temp
    humidity: hum
  - platform: template
    name: "Dew Point"
    lambda: |-
      return (243.5*(log(id(hum).state/100)+((17.67*id(temp).state)/
      (243.5+id(temp).state)))/(17.67-log(id(hum).state/100)-
      ((17.67*id(temp).state)/(243.5+id(temp).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'