substitutions:
  name: "presencemod-ld2410"
  friendly_name: "Sensore movimento"

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key

esphome:
  name: "$name"
  friendly_name: "$friendly_name"
  name_add_mac_suffix: true
#  build_path: ./build/${name}
  project:
    name: "papperone.presence-ld2410"
    version: "0.1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_improv:
  authorizer: none

improv_serial:

dashboard_import:
  package_import_url: github://papperone/ESPresenceLD/ESPresenceLD.yaml@main
  import_full_config: false # or true


wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
# non occorre, di default prenderà il devicename   ssid: "LD2410_TestBoard"
    password: "12345678"

captive_portal:

# Enable logging
logger:
#  hardware_uart: uart0

# Enable Home Assistant API
api:

ota:

#web_server:
#  port: 80


light:
  - platform: status_led
    entity_category: config
    name: "Status LED ESP32"
    pin: GPIO13

button:
  - platform: restart
    entity_category: diagnostic
    icon: mdi:power-cycle
    name: "ESP reboot"
  - platform: restart
    entity_category: diagnostic
    icon: mdi:power-cycle
    name: "ESP reboot"
  - platform: factory_reset
    name: Restart with Factory Default Settings