substitutions:
  name: ssr-2-relays
  friendly_name: Relay SSR2
  project_name: raidnet.ssr2
  project_version: 1.0.0
  comment: comment

  log_level: debug
  disable_entities:  'true' # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password
  

esp8266:
  board: esp01_1m

packages:
# Common Remote Packages
  base: github://raidnet-ms/homenest/common/device_base.yaml@main
  chip: github://raidnet-ms/homenest/common/board/common-8266.yaml@main
#  board: github://raidnet-ms/homenest/common/board/esp01s.yaml
  diagnostic: github://raidnet-ms/homenest/common/diagnostic.yaml@main

# Disabilita UART per liberare GPIO1/GPIO3
logger:
  baud_rate: 0

# Relè
switch:
  - platform: gpio
    pin: GPIO0
    name: "SSR2 Relay"
  - platform: gpio
    pin: GPIO2
    name: "SSR1 Relay"

# Pulsanti
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    name: "Switch 1"
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Switch 2"