substitutions:
  devicename: termostato
  upper_devicename: Termostato Casa
##############################
esphome:
  project:
    name: "marco.$devicename"
    version: "1.0.0"

packages:
    device_base: !include common/board/esp01s.yaml
#    wifi:     !include common/wifi.yaml
#################################################################

status_led:
  pin:
    number: 2
    inverted: false
  id: led
  
binary_sensor:
  - platform: gpio
    pin: 
      number: 1
      mode: INPUT_PULLUP
      inverted: True
    name: "Pulsante accensione"
    on_release:
      - switch.toggle: switch_t1

switch:
    platform: gpio
    pin: 0
    id: switch_t1
    
climate:
    platform: thermostat
    name: "$upper_devicename"
    sensor: temp01
    default_target_temperature_low: 20 °C
    heat_action:
      - switch.turn_on: switch_t1
    idle_action:
      - switch.turn_off: switch_t1
    min_idle_time: 600s
    min_heating_off_time: 300s
    min_heating_run_time: 120s

      
sensor:
    platform: dht
    model: am2302
    pin: 3
    temperature:
      name: "Sensore temperatura"
      id: temp01
      unit_of_measurement: "°C"
      filters:
        - calibrate_linear:
#       # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 26 -> 24.7
    humidity:
      name: "Sensore umidità"
#      filters:
#      - calibrate_linear:
#          # Map 0 (from sensor) to 0 (true value)
#          - 0 -> 0
#          - 66 -> 67
#    update_interval: 60s