substitutions:
  devicename: termostato_nosensor
  upper_devicename: Termostato Bagno
###############################
  
esphome:
  project:
    name: "marco.$devicename"
    version: "1.0.0"

packages:
    device_base: !include common/board/esp01s.yaml
#    wifi:     !include common/wifi.yaml
#################################################################

status_led:
  pin:
    number: 2
    inverted: false
  id: led

switch:
    platform: gpio
    name: "heater"
    pin: 0
    id: switch_termostato
    
climate:
    platform: thermostat
    name: Termostato
    sensor: inside_temperature_ns
    default_target_temperature_low: 20 °C
    heat_action:
      - switch.turn_on: switch_termostato
    idle_action:
      - switch.turn_off: switch_termostato
    min_idle_time: 600s
    min_heating_off_time: 300s
    min_heating_run_time: 120s
      

sensor:
  - platform: homeassistant
    id: inside_temperature_ns
    entity_id: sensor.sensore_temperatura_bagno
    internal: true