substitutions:
  name: termometro-dht11
  friendly_name: termometro-dht11
  project_name: raidnet.dht11
  project_version: 1.0.0
  comment: Termometro dht11 su esp01

  log_level: debug
  disable_entities:  'true' # Disabilitare in blocco entità superflue
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password


captive_portal:

packages:
# Common Remote Packages
  base: github://raidnet-ms/homenest/common/device_base.yaml@main
  chip: github://raidnet-ms/homenest/common/board/common-8266.yaml@main
  board: github://raidnet-ms/homenest/common/board/esp01s.yaml
  diagnostic: github://raidnet-ms/homenest/common/diagnostic.yaml@main

output:
  - platform: gpio
    pin: GPIO1
    id: led_gpio

light:
  - platform: binary
    name: "LED ESP01"
    output: led_gpio

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT11
    temperature:
      name: "Temperatura DHT11 Raw"
      id: dht_temp_raw
    humidity:
      name: "Umidità DHT11 Raw"
      id: dht_hum_raw
    update_interval: 30s

  # Template sensor per temperatura con fallback
  - platform: template
    name: "Temperatura DHT11"
    id: dht_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 30s
    lambda: |-
      if (isnan(id(dht_temp_raw).state)) {
        // Mantieni ultimo valore valido
        return id(dht_temp).state;
      } else {
        return id(dht_temp_raw).state;
      }

  # Template sensor per umidità con fallback
  - platform: template
    name: "Umidità DHT11"
    id: dht_hum
    unit_of_measurement: "%"
    accuracy_decimals: 1
    update_interval: 30s
    lambda: |-
      if (isnan(id(dht_hum_raw).state)) {
        return id(dht_hum).state;
      } else {
        return id(dht_hum_raw).state;
      }