sensor:
  - platform: template
    id: irrigation_av_state
    name: "Remaining active valve"
    icon: "mdi:timer-sand"
    device_class: duration
    unit_of_measurement: s
    update_interval: 1s
    lambda: return (id(giardino).time_remaining_active_valve().value());
  - platform: template
    id: irrigation_state
    name: "Remaining current operation"
    icon: "mdi:timer-sand"
    device_class: duration
    unit_of_measurement: s
    update_interval: 1s
    lambda: return (id(giardino).time_remaining_current_operation());


sprinkler:
  - id: giardino
    main_switch: "Avvia ciclo irrigazione"
    auto_advance_switch: "Avanzamento automatico"
    standby_switch: "Pausa"
    repeat_number:
      name: "Ripeti ciclo"
      min_value: 0
      max_value: 5
    next_prev_ignore_disabled: true
#    queue_enable_switch: "Abilita coda"
#    reverse_switch: "Inverti ordine"
    valve_pulse_duration: 800ms
#    valve_overlap: 2s
#   valve_open_delay: 5s
    valves:
      - valve_switch: "Avvia $zonename_A"
        enable_switch: "Abilita $zonename_A"
        #icon: mdi:carrot
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_A"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_A
          restore_value: true
          unit_of_measurement: min
        valve_switch_id: valve1


      - valve_switch: "Avvia $zonename_B"
        enable_switch: "Abilita $zonename_B"
#        icon: mdi:sprout
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_B"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_B
          restore_value: true
          unit_of_measurement: min
        valve_switch_id: valve2

      - valve_switch: "Avvia $zonename_C"
        enable_switch: "Abilita $zonename_C"
#        icon: mdi:carrot
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_C"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_C
          restore_value: true
          unit_of_measurement: min
        valve_switch_id: valve3

      - valve_switch: "Avvia $zonename_D"
        enable_switch: "Abilita $zonename_D"
#        icon: mdi:sprinkler
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_D"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_D
          restore_value: true
          unit_of_measurement: min
        valve_switch_id: valve4


# Timer segnapassi
number:
  - platform: template
    name: "Timer segnapassi"
    step: 30
    min_value: 30
    max_value: 300
    id: timer_light
    optimistic: true
    restore_value: true
    unit_of_measurement: s
    icon: mdi:timer
    entity_category: config