# in teoria questo file andrebbe su github e dovrebbe essere collegato al file config disponibile sui device client
substitutions:
  name: sprinkler
  friendly_name: Irrigatore
  project_name: raidnet.alligator
  project_version: 1.0.0
  comment: comment
  # Options
  disable_entities: 'true' # disable unnecessary entities by default
  log_level: debug

  #wifi_ssid: !secret wifi_ssid
  #wifi_password: !secret wifi_password
  #api_key: !secret api_key
  #ota_password: !secret ota_password

  zonename_A: A - Null  # vedere se posso inserirle come config in esphome text
  zonename_B: B - Siepe
  zonename_C: C - Orto
  zonename_D: D - Prato


# Device GPIO
  light_pin: GPIO1
# aggiungere i gpio dello sprinkler

sensor:
  - platform: template
    id: irrigation_av_state
    name: "Remaining active valve"
    icon: "mdi:timer-sand"
    device_class: duration
    unit_of_measurement: s
    update_interval: 1s
    lambda: return (id(giardino).time_remaining_active_valve().value());
  - platform: template
    id: irrigation_state
    name: "Remaining current operation"
    icon: "mdi:timer-sand"
    device_class: duration
    unit_of_measurement: s
    update_interval: 1s
    lambda: return (id(giardino).time_remaining_current_operation());


sprinkler:
  - id: giardino
    main_switch: "Avvia ciclo irrigazione"
    auto_advance_switch: "Avanzamento automatico"
    standby_switch: "Pausa"
    repeat_number:
      name: "Ripeti ciclo"
      min_value: 0
      max_value: 5
    next_prev_ignore_disabled: true
#    queue_enable_switch: "Abilita coda"
#    reverse_switch: "Inverti ordine"
    valve_pulse_duration: 800ms
#    valve_overlap: 2s
#   valve_open_delay: 5s
    valves:
      - valve_switch: "Avvia $zonename_A"
        enable_switch: "Abilita $zonename_A"
        #icon: mdi:carrot
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_A"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_A
          restore_value: true
          unit_of_measurement: min
#        valve_switch_id: valve_A
        valve_on_switch_id: a_on
        valve_off_switch_id: a_off
      - valve_switch: "Avvia $zonename_B"
        enable_switch: "Abilita $zonename_B"
#        icon: mdi:sprout
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_B"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_B
          restore_value: true
          unit_of_measurement: min
#        valve_switch_id: valve_B
        valve_on_switch_id: b_on
        valve_off_switch_id: b_off
      - valve_switch: "Avvia $zonename_C"
        enable_switch: "Abilita $zonename_C"
#        icon: mdi:carrot
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_C"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_C
          restore_value: true
          unit_of_measurement: min
#        valve_switch_id: valve_C
        valve_on_switch_id: c_on
        valve_off_switch_id: c_off
      - valve_switch: "Avvia $zonename_D"
        enable_switch: "Abilita $zonename_D"
#        icon: mdi:sprinkler
        run_duration_number:
          icon: mdi:timer
          name: "Timer $zonename_D"
          step: 1
          initial_value: 5
          min_value: 1
          max_value: 30
          id: timer_D
          restore_value: true
          unit_of_measurement: min
#        valve_switch_id: valve_D
        valve_on_switch_id: d_on
        valve_off_switch_id: d_off