text:
  - platform: template
    name: "Casa"
    optimistic: true
    initial_value: None
    min_length: 3
    max_length: 10
    mode: text
    restore_value: 'true'
    id: housename # verificare se accetta ID