substitutions:
  board: esp32cam
  flashlight: Flash light
  led_name: Wifi Status led
  project_name: raidnet.esp32cam
  project_version: 1.0.0
  comment: Esp32cam AI Thinker version

esp32_camera:
  name: $friendly_name
  external_clock:
    pin: GPIO0
    frequency: 10MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32


# Image/Video settings, https://esphome.io/components/esp32_camera.html
  max_framerate: 25 fps    # default: 10 fps, max 60
  idle_framerate: 0.2 fps # default: 0.1 fps - framerate for 'picture' in HA dashboard
  resolution: 1024x768 #(QVGA, VGA, SVGA, XGA, SXGA, UXGA)
#  jpeg_quality: 10
  vertical_flip: False
#  contrast: 0 # default: 0, variable -2 to 2
#  brightness: 0 # default: 0, variable -2 to 2
#  saturation: 0 # default: 0, variable -2 to 2
#  frame_buffer_count: 2    # 1 o 2 buffer
  frame_buffer_location: PSRAM
#  test_pattern: true
  name: My Camera

# Server video/pictures, https://esphome.io/components/esp32_camera_web_server.html
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot


output:
# Flashlight
  - platform: gpio
    pin: GPIO4
    id: gpio_4
# Status led Wifi Connection
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    id: gpio_33

light:
  - platform: binary
    output: gpio_4
    name: $flashlight
#statuslight led 33 for wifi connect
  - platform: binary
    output: gpio_33
    name: $led_name